export const envConst = {
  DB_TYPE: 'DB_TYPE',
  DB_HOST: 'DB_HOST',
  DB_PORT: 'DB_PORT',
  DB_PASSWORD: 'DB_PASSWORD',
  DB_USERNAME: 'DB_USERNAME',
  DB_DATABASE: 'DB_DATABASE',
  APP_PORT: 'APP_PORT',
  JWT_SECRET: 'JWT_SECRET',
  JWT_EXPIRES_IN: 'JWT_EXPIRES_IN',
};
